# symptom_data.py

sti_questions = [
    {"question": "Have you had unprotected sex recently?", "risk_weight": 2},
    {"question": "Are you experiencing any unusual genital discharge?", "risk_weight": 2},
    {"question": "Do you feel pain or burning during urination?", "risk_weight": 1},
    {"question": "Do you have sores or bumps around your genitals?", "risk_weight": 3},
    {"question": "Have you experienced itching in your genital area?", "risk_weight": 1},
    {"question": "Have you or your partner tested positive for an STI?", "risk_weight": 3},
    {"question": "Do you have pain during sex?", "risk_weight": 2},
    {"question": "Are you experiencing pelvic pain?", "risk_weight": 2},
    {"question": "Have you had multiple sexual partners in the last 6 months?", "risk_weight": 2},
    {"question": "Have you ever been diagnosed with an STI before?", "risk_weight": 2},
    {"question": "Has your partner had multiple sexual partners?", "risk_weight": 2},
    {"question": "Do you engage in oral or anal sex without protection?", "risk_weight": 2},
    {"question": "Have you noticed unusual bleeding between periods?", "risk_weight": 2},
    {"question": "Have you experienced lower back pain recently?", "risk_weight": 1},
    {"question": "Do you share needles or other drug equipment?", "risk_weight": 3},
    {"question": "Do you experience pain in your testicles or scrotum?", "risk_weight": 2},
    {"question": "Have you had a one-night stand recently?", "risk_weight": 2},
    {"question": "Has your partner shown any STI symptoms?", "risk_weight": 3},
    {"question": "Do you avoid regular STI testing?", "risk_weight": 2},
    {"question": "Have you experienced flu-like symptoms after sexual contact?", "risk_weight": 1},
    {"question": "Have you ever been treated for an STI but symptoms returned?", "risk_weight": 2},
    {"question": "Have you had sex with someone whose STI status you didn’t know?", "risk_weight": 2},
    {"question": "Do you have swollen lymph nodes in the groin area?", "risk_weight": 2},
    {"question": "Do you avoid using condoms consistently?", "risk_weight": 3},
    {"question": "Have you noticed rashes on your body or hands?", "risk_weight": 1},
    {"question": "Have you recently experienced fever after sex?", "risk_weight": 1},
    {"question": "Do you engage in sex work or exchange sex for favors?", "risk_weight": 3},
    {"question": "Do you suspect your partner may be unfaithful?", "risk_weight": 2},
]

pregnancy_questions = [
    {"question": "Did you miss your last menstrual period?", "risk_weight": 3},
    {"question": "Have you had unprotected sex in the last month?", "risk_weight": 2},
    {"question": "Are your breasts tender or swollen?", "risk_weight": 1},
    {"question": "Are you experiencing nausea or vomiting?", "risk_weight": 2},
    {"question": "Do you feel more tired than usual?", "risk_weight": 1},
    {"question": "Have you noticed frequent urination?", "risk_weight": 1},
    {"question": "Are you feeling mood swings?", "risk_weight": 1},
    {"question": "Do you feel bloated?", "risk_weight": 1},
    {"question": "Did your period come later than usual?", "risk_weight": 2},
    {"question": "Have you had a lighter or shorter period than normal?", "risk_weight": 2},
    {"question": "Have you had unprotected sex during your fertile window?", "risk_weight": 3},
    {"question": "Are you currently not using any birth control method?", "risk_weight": 3},
    {"question": "Do you have cramps but no bleeding?", "risk_weight": 2},
    {"question": "Have you felt more emotional or tearful lately?", "risk_weight": 1},
    {"question": "Are you experiencing food aversions or cravings?", "risk_weight": 2},
    {"question": "Have you experienced dizziness or fainting?", "risk_weight": 1},
    {"question": "Do you feel more sensitive to smells than usual?", "risk_weight": 2},
    {"question": "Do you have a history of irregular periods?", "risk_weight": 1},
    {"question": "Did your partner ejaculate inside you during sex?", "risk_weight": 3},
    {"question": "Have you taken emergency contraception recently?", "risk_weight": 2},
    {"question": "Do you experience a metallic taste in your mouth?", "risk_weight": 1},
    {"question": "Have you taken a pregnancy test recently?", "risk_weight": 1},
    {"question": "Are your clothes feeling tighter around the abdomen?", "risk_weight": 1},
    {"question": "Have you had any light spotting instead of a period?", "risk_weight": 2},
    {"question": "Do you feel pressure or tightness in your lower abdomen?", "risk_weight": 1},
    {"question": "Have you experienced constipation recently?", "risk_weight": 1},
    {"question": "Have you noticed a change in your appetite?", "risk_weight": 1},
    {"question": "Have you stopped using hormonal birth control?", "risk_weight": 2},

]