[theme]
base = "light"
primaryColor = "#7e57c2"
backgroundColor = "#f8f5ff"
secondaryBackgroundColor = "#f3eaff"
textColor = "#000000"
font = "sans serif"

[ui]
hideTopBar = true

[server]
enableStaticServing = true
