[theme]
base = "light"
primaryColor = "#7e57c2"
backgroundColor = "#f8f5ff"
secondaryBackgroundColor = "#f3eaff"
textColor = "#000000"
font = "sans serif"

[server]
fileWatcherType = "none"
enableStaticServing = true

[ui]
hideTopBar = true
browser.gatherUsageStats = false
